QUIZ = {
    "DSA": [
        ("Binary search time complexity?", ["O(n)", "O(log n)", "O(n log n)", "O(1)"], "O(log n)"),
        ("FIFO structure?", ["Stack", "Queue", "Tree", "Graph"], "Queue"),
        ("LIFO structure?", ["Queue", "Stack", "Array", "Tree"], "Stack"),
        ("Worst case of quicksort?", ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], "O(n^2)"),
        ("Traversal gives sorted BST?", ["Preorder", "Postorder", "Inorder", "Level"], "Inorder"),
        ("Used in recursion?", ["Queue", "Stack", "Heap", "Graph"], "Stack"),
        ("Not linear DS?", ["Array", "Stack", "Queue", "Tree"], "Tree"),
        ("BFS uses?", ["Stack", "Queue", "Heap", "Array"], "Queue"),
        ("DFS uses?", ["Queue", "Stack", "Heap", "Array"], "Stack"),
        ("BST full form?", ["Binary Search Tree", "Base Tree", "Binary Sorted", "Balanced Tree"], "Binary Search Tree"),
        ("Graph uses edges and?", ["Nodes", "Vertices", "Points", "Links"], "Vertices"),
        ("Heap is?", ["Binary Tree", "BST", "Complete Tree", "Graph"], "Complete Tree"),
        ("Queue deletion?", ["Front", "Rear", "Middle", "Any"], "Front"),
        ("Stack overflow?", ["Push full", "Pop empty", "Peek", "Top"], "Push full"),
        ("Array index starts?", ["0", "1", "-1", "Depends"], "0"),
        ("Adjacency matrix is?", ["2D", "1D", "3D", "List"], "2D"),
        ("Hashing improves?", ["Speed", "Memory", "Size", "Security"], "Speed"),
        ("Collision occurs in?", ["Stack", "Queue", "Hashing", "Tree"], "Hashing"),
        ("AVL tree is?", ["Balanced BST", "Heap", "Graph", "Trie"], "Balanced BST"),
        ("Queue insertion?", ["Rear", "Front", "Middle", "None"], "Rear"),
        ("Time complexity of merge sort?", ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], "O(n log n)"),
        ("Binary tree max children?", ["1", "2", "3", "Any"], "2"),
        ("Sparse graph has?", ["Few edges", "Many edges", "Complete", "None"], "Few edges"),
        ("Which is non-linear?", ["Array", "Stack", "Queue", "Tree"], "Tree"),
        ("Circular queue advantage?", ["Memory reuse", "Fast", "Simple", "None"], "Memory reuse"),
    ],

    "OOPS": [
        ("Encapsulation means?", ["Binding data & methods", "Hiding code", "Reuse", "Multiple forms"], "Binding data & methods"),
        ("Inheritance provides?", ["Reuse", "Security", "Speed", "Memory"], "Reuse"),
        ("Abstraction hides?", ["Implementation", "Data", "Objects", "Files"], "Implementation"),
        ("Polymorphism means?", ["Many forms", "Inheritance", "Binding", "Hiding"], "Many forms"),
        ("Base class is?", ["Parent", "Child", "Derived", "Object"], "Parent"),
        ("Overloading is?", ["Compile time", "Runtime", "Link time", "Load time"], "Compile time"),
        ("Overriding is?", ["Runtime", "Compile", "Static", "Final"], "Runtime"),
        ("Destructor symbol?", ["~", "!", "#", "$"], "~"),
        ("Which is not OOP?", ["Java", "Python", "C", "C++"], "C"),
        ("Object is?", ["Instance", "Class", "Method", "Function"], "Instance"),
        ("Class is?", ["Blueprint", "Object", "Data", "Variable"], "Blueprint"),
        ("Constructor name?", ["Class name", "Object", "Init", "Create"], "Class name"),
        ("Virtual functions support?", ["Runtime polymorphism", "Compile", "Static", "Inline"], "Runtime polymorphism"),
        ("Private members accessible?", ["Same class", "Anywhere", "Derived", "Outside"], "Same class"),
        ("Public members accessible?", ["Anywhere", "Class only", "Derived", "None"], "Anywhere"),
        ("Protected accessible?", ["Derived", "Outside", "None", "Main"], "Derived"),
        ("Multiple inheritance supported in?", ["C++", "Java", "Python", "All"], "C++"),
        ("Interface has?", ["Pure virtual", "Variables", "Objects", "Memory"], "Pure virtual"),
        ("Abstract class has?", ["Abstract methods", "Objects", "Main", "None"], "Abstract methods"),
        ("Static belongs to?", ["Class", "Object", "Method", "None"], "Class"),
        ("Final prevents?", ["Inheritance", "Execution", "Compilation", "Linking"], "Inheritance"),
        ("this keyword refers?", ["Current object", "Class", "Method", "Variable"], "Current object"),
        ("super refers?", ["Parent", "Child", "Class", "Object"], "Parent"),
        ("Friend function?", ["Access private", "Inherit", "Override", "Virtual"], "Access private"),
        ("Encapsulation improves?", ["Security", "Speed", "Memory", "UI"], "Security"),
    ],

    "DBMS": [
    ("Primary key is?", ["Unique", "Null", "Duplicate", "Optional"], "Unique"),
    ("Foreign key refers to?", ["Primary key", "Candidate key", "Composite key", "Super key"], "Primary key"),
    ("SQL stands for?", ["Structured Query Language", "Simple Query Language", "Standard Query List", "Sequential Query Language"], "Structured Query Language"),
    ("Which command removes table?", ["DELETE", "DROP", "TRUNCATE", "REMOVE"], "DROP"),
    ("DELETE removes?", ["Rows", "Columns", "Table", "Database"], "Rows"),
    ("Which clause filters rows?", ["WHERE", "ORDER BY", "GROUP BY", "HAVING"], "WHERE"),
    ("1NF removes?", ["Repeating groups", "Partial dependency", "Transitive dependency", "None"], "Repeating groups"),
    ("2NF removes?", ["Partial dependency", "Repeating groups", "Transitive dependency", "None"], "Partial dependency"),
    ("3NF removes?", ["Transitive dependency", "Partial dependency", "Repeating groups", "None"], "Transitive dependency"),
    ("Which is not a DBMS?", ["MySQL", "Oracle", "MongoDB", "Python"], "Python"),
    ("ACID property A?", ["Atomicity", "Accuracy", "Availability", "Access"], "Atomicity"),
    ("Join combines?", ["Tables", "Rows", "Columns", "Indexes"], "Tables"),
    ("Which join returns common records?", ["Inner", "Left", "Right", "Full"], "Inner"),
    ("Which command adds data?", ["INSERT", "ADD", "PUT", "UPDATE"], "INSERT"),
    ("Index improves?", ["Speed", "Memory", "Security", "Storage"], "Speed"),
    ("Schema defines?", ["Structure", "Data", "Keys", "Queries"], "Structure"),
    ("Candidate key?", ["Possible primary key", "Foreign key", "Composite", "Null"], "Possible primary key"),
    ("View is?", ["Virtual table", "Real table", "Index", "Schema"], "Virtual table"),
    ("Tuple means?", ["Row", "Column", "Table", "Key"], "Row"),
    ("Attribute means?", ["Column", "Row", "Table", "Key"], "Column"),
    ("Which is DDL?", ["CREATE", "SELECT", "INSERT", "UPDATE"], "CREATE"),
    ("Which is DML?", ["INSERT", "CREATE", "DROP", "ALTER"], "INSERT"),
    ("Which clause groups rows?", ["GROUP BY", "WHERE", "ORDER BY", "HAVING"], "GROUP BY"),
    ("HAVING works on?", ["Groups", "Rows", "Tables", "Columns"], "Groups"),
    ("Normalization reduces?", ["Redundancy", "Speed", "Security", "Queries"], "Redundancy"),
],
    "OS": [
    ("OS stands for?", ["Operating System", "Open Software", "Online System", "Order System"], "Operating System"),
    ("Which is not OS?", ["Linux", "Windows", "Oracle", "MacOS"], "Oracle"),
    ("FCFS scheduling is?", ["Non-preemptive", "Preemptive", "Priority", "Round Robin"], "Non-preemptive"),
    ("Round Robin is?", ["Preemptive", "Non-preemptive", "Static", "Batch"], "Preemptive"),
    ("Deadlock needs?", ["4 conditions", "3 conditions", "2 conditions", "1 condition"], "4 conditions"),
    ("Which avoids deadlock?", ["Banker’s", "FCFS", "SJF", "Priority"], "Banker’s"),
    ("Paging removes?", ["External fragmentation", "Internal fragmentation", "Deadlock", "Starvation"], "External fragmentation"),
    ("Thrashing occurs due to?", ["High paging", "Low memory", "CPU idle", "I/O wait"], "High paging"),
    ("Context switching is?", ["Process switch", "Thread kill", "Memory clear", "Disk write"], "Process switch"),
    ("Semaphore is?", ["Synchronization tool", "Scheduler", "Memory", "CPU"], "Synchronization tool"),
    ("Which is real-time OS?", ["RTOS", "Linux", "Windows", "DOS"], "RTOS"),
    ("Kernel is?", ["Core of OS", "UI", "Driver", "Shell"], "Core of OS"),
    ("Process has?", ["PCB", "TCB", "File", "Pipe"], "PCB"),
    ("Thread shares?", ["Memory", "CPU", "Disk", "I/O"], "Memory"),
    ("Multitasking means?", ["Multiple tasks", "Multiple users", "Multiple CPUs", "Multiple OS"], "Multiple tasks"),
    ("Starvation occurs due to?", ["Priority", "Deadlock", "Paging", "Segmentation"], "Priority"),
    ("System call used for?", ["OS service", "Compile", "Link", "Execute"], "OS service"),
    ("Virtual memory uses?", ["Disk", "Cache", "Register", "ROM"], "Disk"),
    ("Which is scheduling algo?", ["SJF", "DFS", "BFS", "Dijkstra"], "SJF"),
    ("Time sharing improves?", ["Response time", "Memory", "Security", "I/O"], "Response time"),
    ("Which is not scheduling?", ["FCFS", "SJF", "FIFO", "LRU"], "LRU"),
    ("Critical section problem relates to?", ["Synchronization", "Deadlock", "Memory", "CPU"], "Synchronization"),
    ("Mutex is?", ["Binary semaphore", "Scheduler", "Thread", "Queue"], "Binary semaphore"),
    ("Swapping moves process to?", ["Disk", "Cache", "CPU", "RAM"], "Disk"),
    ("OS boots via?", ["Bootloader", "Kernel", "Shell", "BIOS"], "Bootloader"),
],
    "Python": [
    ("Python is?", ["Interpreted", "Compiled", "Hybrid", "Binary"], "Interpreted"),
    ("Which is immutable?", ["List", "Set", "Tuple", "Dict"], "Tuple"),
    ("Function keyword?", ["def", "func", "define", "function"], "def"),
    ("Which loop exists?", ["for", "while", "do-while", "repeat"], "for"),
    ("Index starts at?", ["0", "1", "-1", "Depends"], "0"),
    ("Which creates list?", ["[]", "{}", "()", "<>"], "[]"),
    ("None means?", ["No value", "Zero", "Empty", "False"], "No value"),
    ("PEP stands for?", ["Python Enhancement Proposal", "Program Execution Plan", "Python Easy Project", "None"], "Python Enhancement Proposal"),
    ("Which is dictionary?", ["{}", "[]", "()", "<>"], "{}"),
    ("Lambda is?", ["Anonymous function", "Class", "Module", "Decorator"], "Anonymous function"),
    ("len() returns?", ["Length", "Index", "Value", "Size"], "Length"),
    ("Which handles exception?", ["try-except", "if-else", "for", "while"], "try-except"),
    ("List comprehension is?", ["Compact loop", "Class", "Function", "Module"], "Compact loop"),
    ("Which is mutable?", ["List", "Tuple", "String", "Int"], "List"),
    ("Import keyword?", ["import", "include", "using", "require"], "import"),
    ("__init__ is?", ["Constructor", "Destructor", "Method", "Class"], "Constructor"),
    ("range() returns?", ["Sequence", "List", "Tuple", "Set"], "Sequence"),
    ("Which file extension?", [".py", ".java", ".cpp", ".js"], ".py"),
    ("Which is OOP?", ["Python", "C", "Assembly", "HTML"], "Python"),
    ("Indentation used for?", ["Block", "Loop", "Class", "Import"], "Block"),
    ("Which is module?", ["math", "int", "print", "if"], "math"),
    ("Global keyword?", ["global", "static", "extern", "public"], "global"),
    ("Pass means?", ["Do nothing", "Stop", "Exit", "Break"], "Do nothing"),
    ("Which creates set?", ["{}", "set()", "[]", "()"], "set()"),
    ("Garbage collection handles?", ["Memory", "CPU", "I/O", "Disk"], "Memory"),
],
    "Java": [
    ("Java is?", ["Platform independent", "Dependent", "Low-level", "Script"], "Platform independent"),
    ("JVM stands for?", ["Java Virtual Machine", "Java Variable Method", "Joint Virtual Machine", "None"], "Java Virtual Machine"),
    ("Java file extension?", [".java", ".class", ".jar", ".exe"], ".java"),
    ("Which supports inheritance?", ["extends", "implements", "inherits", "uses"], "extends"),
    ("Interface keyword?", ["interface", "implements", "abstract", "extends"], "interface"),
    ("Java is?", ["OOP", "POP", "Procedural", "Assembly"], "OOP"),
    ("Which is not OOP?", ["C", "Java", "Python", "C++"], "C"),
    ("Constructor name?", ["Class name", "Object", "Init", "New"], "Class name"),
    ("Method overloading?", ["Compile time", "Runtime", "Link", "Load"], "Compile time"),
    ("Method overriding?", ["Runtime", "Compile", "Static", "Inline"], "Runtime"),
    ("Multiple inheritance via?", ["Interface", "Class", "Object", "Package"], "Interface"),
    ("Final keyword prevents?", ["Inheritance", "Compilation", "Execution", "Loading"], "Inheritance"),
    ("Static belongs to?", ["Class", "Object", "Method", "None"], "Class"),
    ("Which collection is ordered?", ["List", "Set", "Map", "Queue"], "List"),
    ("Which is checked exception?", ["IOException", "NullPointer", "Arithmetic", "Index"], "IOException"),
    ("Java package is?", ["Namespace", "Library", "Class", "Method"], "Namespace"),
    ("Garbage collector manages?", ["Memory", "CPU", "Disk", "Threads"], "Memory"),
    ("String is?", ["Immutable", "Mutable", "Dynamic", "Static"], "Immutable"),
    ("Main method returns?", ["void", "int", "String", "Object"], "void"),
    ("Which keyword creates object?", ["new", "create", "alloc", "make"], "new"),
    ("Array index starts?", ["0", "1", "-1", "Depends"], "0"),
    ("Which is thread?", ["Runnable", "Scanner", "String", "Math"], "Runnable"),
    ("Java supports pointers?", ["No", "Yes", "Limited", "Hidden"], "No"),
    ("JDK includes?", ["JRE + tools", "JVM only", "Compiler only", "None"], "JRE + tools"),
    ("Access modifier for all?", ["public", "private", "protected", "default"], "public"),
],
    "JavaScript": [
    ("JavaScript runs in?", ["Browser", "Compiler", "OS", "CPU"], "Browser"),
    ("JS is?", ["Interpreted", "Compiled", "Hybrid", "Binary"], "Interpreted"),
    ("Which declares variable?", ["var", "int", "define", "let"], "var"),
    ("let scope?", ["Block", "Global", "Function", "Static"], "Block"),
    ("const value?", ["Cannot change", "Mutable", "Dynamic", "Undefined"], "Cannot change"),
    ("Which is not JS?", ["Java", "ECMAScript", "JS", "Node"], "Java"),
    ("DOM stands for?", ["Document Object Model", "Data Object Method", "Digital Order Model", "None"], "Document Object Model"),
    ("Which outputs console?", ["console.log()", "print()", "echo()", "write()"], "console.log()"),
    ("Array index starts?", ["0", "1", "-1", "Depends"], "0"),
    ("== checks?", ["Value", "Type", "Both", "None"], "Value"),
    ("=== checks?", ["Value & type", "Value", "Type", "None"], "Value & type"),
    ("NaN means?", ["Not a Number", "Null and None", "Negative", "No argument"], "Not a Number"),
    ("JS is?", ["Dynamic", "Static", "Strict", "Binary"], "Dynamic"),
    ("Which loop exists?", ["for", "foreach", "repeat", "until"], "for"),
    ("Function keyword?", ["function", "def", "func", "method"], "function"),
    ("Arrow function uses?", ["=>", "->", "::", "**"], "=>"),
    ("Which is event?", ["onclick", "onload", "onchange", "All"], "All"),
    ("JSON stands for?", ["JavaScript Object Notation", "Java Source Object Name", "None", "Data"], "JavaScript Object Notation"),
    ("Local storage stores?", ["Key-value", "Objects", "Files", "Cache"], "Key-value"),
    ("Which is framework?", ["React", "HTML", "CSS", "SQL"], "React"),
    ("JS runs on server via?", ["Node.js", "Apache", "JVM", "PHP"], "Node.js"),
    ("Which keyword stops loop?", ["break", "stop", "exit", "return"], "break"),
    ("Undefined means?", ["Not assigned", "Null", "Zero", "False"], "Not assigned"),
    ("Which converts string to int?", ["parseInt()", "int()", "Number()", "toInt()"], "parseInt()"),
    ("Which handles async?", ["Promise", "Loop", "Thread", "Block"], "Promise"),
],
}